### ISSUE TITLE
issue concerning implanting new dataset in GaLR

### ISSUE THREAD

**Issue by fine1998** [xiaoyuan1996/GaLR#1]
Recently, I've been trying to reproduce your result while implanting a few more datasets and cite your work in my paper. Could you please tell me how can I generate the .npy file for a new dataset.

Best regards!

**Comment by xiaoyuan1996** [comment]
Sorry for late reply. 

In this paper, we adopt a detection model that pre-trained on the DOTA dataset based on the Paddle framework to first extract the instance targets of the sliced images, and then use the DREA mechanism to merge and reduce the proposed local features. These local features are then stored as npy files for subsequent processing and calling by the GCN model. Since the work has been over for a while, we do not save the previously detected features. As a comparison for the new dataset, we recommend that you use the detectors mentioned in the paper to extract objects, and then generate corresponding features according to the feature processing strategies mention in the paper. 

Regarding the format stored by npy, we recommend that you directly use numpy to load and view the provided files. Thank you for acknowledging our work
